/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments/index'
import { Route as DepartmentsIdRouteImport } from './routes/departments/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/departments': typeof DepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/departments/$id' | '/departments/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/departments/$id' | '/departments'
  id: '__root__' | '/' | '/departments/$id' | '/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepartmentsIdRoute: typeof DepartmentsIdRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/departments/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepartmentsIdRoute: DepartmentsIdRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
